# Generated by Django 3.2.6 on 2021-09-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Subcategories',
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcat',
            name='Good',
        ),
        migrations.AddField(
            model_name='good',
            name='subcategory',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcat', to='digiapp.subcat'),
        ),
        migrations.AddField(
            model_name='subcat',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digiapp.category'),
        ),
        migrations.AlterField(
            model_name='good',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcat', to='digiapp.tag'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='digiapp.good'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='digiapp.shoppingcart'),
        ),
    ]
