# Generated by Django 3.2.6 on 2021-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0003_auto_20210920_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='author',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
