# Generated by Django 3.2.6 on 2021-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0004_good_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='average_rating',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='checkout_price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
