# Generated by Django 3.2.6 on 2021-09-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0006_auto_20210921_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='author',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
