# Generated by Django 3.2.6 on 2021-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0007_good_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='good',
            name='color',
            field=models.CharField(choices=[('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('WHITE', 'White'), ('BLACK', 'Black'), ('NOCOLOR', '')], default='NOCOLOR', max_length=9),
        ),
        migrations.AlterField(
            model_name='good',
            name='descritpion',
            field=models.TextField(max_length=2000),
        ),
    ]
