# Generated by Django 3.2.6 on 2021-09-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0008_auto_20210921_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review_text',
        ),
    ]
