# Generated by Django 3.2.6 on 2021-09-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0011_review_written_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='written_time',
            new_name='written_date',
        ),
    ]
