# Generated by Django 3.2.6 on 2021-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiapp', '0012_rename_written_time_review_written_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='written_date',
            field=models.TextField(),
        ),
    ]
